FROM centos

MAINTAINER pavan.avunuri@gmail.com

RUN mkdir /opt/Jenkins/

WORKDIR /opt/Jenkis
#RUN wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
RUN sudo apt-get update
RUN sudo apt-get install jenkins
RUN systemctl enable jenkins
RUN systemctl start jenkins
RUN systemctl status jenkins
RUN yum -y install java
RUN java -version

WORKDIR /opt/tomcat/webapps

EXPOSE 8080

CMD ["/opt/tomcat/bin/catalina.sh", "run"]
